---
layout: post
title: 예외처리
categories: Java복습
---


## 예외처리

사용자의 실수로 인해 발생하는 것을 예외로 생각해보자

스캐너 인스턴스로 nextInt를 호출했는데, 문자가 입력된다면? 

프로그래머는 정수를 입력하길 원했는데, 사용자가 문자를 입력한 상황이다.

이건 사용자의 실수다.

또, 프로그래머는 n1/n2에서 사용자가 n2에 0를 넣지 않을 것이라 생각했지만,

사용자가 0을 넣어버린다면, 그것도 사용자의 실수다.

이러한 상황에서 발생하는 예외에 대해 처리해주는 것이 

try~ catch문이다.

try 블럭안의 문장을 실행하다가 예외가 발생하면 

JVM은 그에 해당하는 예외 클래스의 인스턴스를 생성해서,

catch(Exception e)의 e로 인스턴스를 넘겨준다.

그리고나서 JVM은 catch문 이후의 문장을 이어서 실행한다.
