---
layout: post
title: 예외처리
categories: Java복습
---


## 예외처리

사용자의 실수로 인해 발생하는 것을 예외로 생각해보자

스캐너 인스턴스로 nextInt를 호출했는데, 문자가 입력된다면? 

프로그래머는 정수를 입력하길 원했는데, 사용자가 문자를 입력한 상황이다.

이건 사용자의 실수다.

또, 프로그래머는 n1/n2에서 사용자가 n2에 0를 넣지 않을 것이라 생각했지만,

사용자가 0을 넣어버린다면, 그것도 사용자의 실수다.

이러한 상황에서 발생하는 예외에 대해 처리해주는 것이 

try~ catch문이다.

try 블럭안의 문장을 실행하다가 예외가 발생하면 

JVM은 그에 해당하는 예외 클래스의 인스턴스를 생성해서,

catch(Exception e)의 e로 인스턴스를 넘겨준다.

그리고나서 JVM은 catch문 이후의 문장을 이어서 실행한다.


## Throwable 클래스

모든 예외 클래스의 최상위 클래스이다.

Throwable의 메서드 중에서 2가지 메서드가 있다.

public String getMessage() : 예외의 원인을 담고 있는 문자열 반환

public void printStackTrace() : 예외가 발생한 위치와 호출한 메서드의 정보를 반환


## 예외의 전달

예외 발생 지점에서 예외를 처리하지 않으면,

해당 메서드를 호출한 영역으로 예외가 전달된다.

```
public static void md1(int n){
md2(n,0); //-->md2 메서드를 호출한 곳으로로 넘어온다.
}

public static void md2(int n1,int n2){
int r = n1/ n2 //-->예외 발생 지점인데 처리를 안해줬다.
}

public static void main(String[] args){
md1(3); //--> md2에서 발생한 예외가 이곳 까지 넘어온다.
syso("bye")
}
```


## Exception을 상속하는 예외

직접 예외처리를 하거나, 넘기거나!

RuntimeException은 알아서 넘겨주지만, Exception을 상속하는 예외는 

프로그래머가 직접 처리하거나 메서드를 호출한 곳으로 넘겨줘야한다.

1.IOException

```
  public static void md2() throws IOException
  //md2를 호출한 곳으로 예외를 넘기겠다.


